import { notFound } from "next/navigation";
import { getManagedLease } from "@/lib/lease-access";
import { prisma } from "@/lib/prisma";
import { PrintButton } from "@/components/PrintButton";
import { whatsappLink } from "@/lib/whatsapp";

const fmt = (v: unknown) =>
  Number(v ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const day = (d: Date | null | undefined) => (d ? d.toISOString().slice(0, 10) : "-");

export default async function ReceiptPage({
  params,
}: {
  params: Promise<{ leaseId: string; paymentId: string }>;
}) {
  const { leaseId, paymentId } = await params;
  const { lease } = await getManagedLease(leaseId);

  const payment = await prisma.payment.findFirst({ where: { id: paymentId, leaseId, status: "PAID" } });
  if (!payment) notFound();

  const org = await prisma.organization.findUniqueOrThrow({ where: { id: lease.unit.property.orgId } });
  const period = payment.dueDate.toLocaleString("en-US", { month: "long", year: "numeric" });
  const receiptNo = `R-${payment.id.slice(-8).toUpperCase()}`;
  const wa = whatsappLink(
    lease.tenant.phone,
    `Hello ${lease.tenant.name}, we confirm receipt of KES ${fmt(payment.amount)} for ${lease.unit.property.name} ${lease.unit.label} (${period}). Receipt no. ${receiptNo}. Thank you.`
  );

  return (
    <div className="mx-auto max-w-xl print:max-w-none">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <a href={`/rent/${leaseId}`} className="text-sm text-muted hover:underline">
          ← Back
        </a>
        <div className="flex items-center gap-3">
          {wa && (
            <a href={wa} target="_blank" rel="noopener" className="text-sm font-medium text-accent hover:underline">
              Send on WhatsApp
            </a>
          )}
          <PrintButton />
        </div>
      </div>

      <div className="rounded-lg border border-border bg-surface p-8 print:border-0 print:p-0">
        <div className="flex items-start justify-between gap-4 border-b border-border pb-4">
          <div>
            <p className="font-serif text-2xl text-ink">{org.name}</p>
            <p className="mt-1 text-xs uppercase tracking-wide text-muted">Rent receipt</p>
          </div>
          <div className="text-right text-sm">
            <p className="font-medium text-foreground">{receiptNo}</p>
            <p className="text-xs text-muted">{day(payment.paidDate)}</p>
          </div>
        </div>

        <table className="mt-5 w-full text-sm">
          <tbody>
            <tr>
              <td className="py-1.5 text-muted">Received from</td>
              <td className="py-1.5 text-right">{lease.tenant.name}</td>
            </tr>
            <tr>
              <td className="py-1.5 text-muted">Property</td>
              <td className="py-1.5 text-right">
                {lease.unit.property.name} · {lease.unit.label}
              </td>
            </tr>
            <tr>
              <td className="py-1.5 text-muted">For</td>
              <td className="py-1.5 text-right">Rent, {period}</td>
            </tr>
            <tr>
              <td className="py-1.5 text-muted">Paid by</td>
              <td className="py-1.5 text-right">
                {payment.method}
                {payment.reference ? ` · ${payment.reference}` : ""}
              </td>
            </tr>
            <tr className="border-t-2 border-ink font-serif text-lg text-ink">
              <td className="py-3">Amount received (KES)</td>
              <td className="py-3 text-right">{fmt(payment.amount)}</td>
            </tr>
          </tbody>
        </table>
        {payment.notes && <p className="mt-2 text-xs text-muted">{payment.notes}</p>}
        <p className="mt-8 text-center text-xs text-muted">Thank you. This receipt was generated by PropCo.</p>
      </div>
    </div>
  );
}
